import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Breadcrumbs from "@/components/breadcrumbs";
import Sidebar from "@/components/sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Sidebar>
          <>
            <Breadcrumbs />
            {children}
          </>
        </Sidebar>
      </body>
    </html>
  );
}
